[project]
name = "tickets"
version = "1.0.0"
description = "projet d'entretien, gestion des tickets"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "fastapi[standard]>=0.139.0",
    "sqlalchemy>=2.0",
]

[dependency-groups]
dev = [
    "pytest>=9.1.1",
    "pytest-cov>=7.1.0",
    "ruff>=0.15.21",
]
